export const ADD_SAVE_SERVICE = 'ADD_SAVE_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const RESET_FIELDS = 'RESET_FIELDS';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';